### ISSUE TITLE
Where can I find DeepL API key?

### ISSUE THREAD

**Issue by callmehanu** [atareao/translate-assistant#1]
I installed this extensión, but when I trigger SUPR + T, Fedora show me that notification.
![image](https://user-images.githubusercontent.com/13230502/175845844-57fb9709-7a75-469e-adcc-f524229957bf.png)

**Comment by atareao** [comment]
You must register in DeepL and get an API Key (https://www.deepl.com/es/account/summary)

![imagen](https://user-images.githubusercontent.com/298055/176601405-fd26e9bc-3ff4-411f-b1b3-506455a118b8.png)
