### ISSUE TITLE
translating both ways?

### ISSUE THREAD

**Issue by skillz-xx** [atareao/translate-assistant#6]
hello!

first of all, THANK YOU!
The extension is really useful for me to communicate with spanish speaking friends.
I use it to translate from english to spanish with the deepl api. its great!

just one thing is a bit annoying.. when I need to translate spanish to english, I still need to do it manually,
because I can't find a way to make a second install of the extension to then have another hotkey
and translate english back to spanish..

do you have any suggestions to make translation possible in both ways?

many thankx
Dan

**Comment by atareao** [comment]
I'm working on it... 😊

**Comment by atareao** [comment]
I'm very excited. I added two more options, to paste the content of the clipboard automatically and to translate automatically....

**Comment by atareao** [comment]
Updated in version 9....

**Comment by skillz-xx** [comment]
ohhhhh wow...  that will help me a lot, if it works well in gnome 44 / ubuntu 23.04 , I will make a donation for you for this very helpful tool!!

**Comment by skillz-xx** [comment]
hi again, I updated the extension, but I cannot see the "Auto options" configuration tab in the settings.. and how would the translation from spanish back to english work exactly?

**Comment by skillz-xx** [comment]
ahhh I have version 8 installed.. which is the one available from the gnome extensions page.. how do I get the version 9?

**Comment by atareao** [comment]
I hope new version will be reviewed in the next hours.... So, I suggest you wait until that.
Thank you

**Comment by skillz-xx** [comment]
I would like to bring this topic back, this would be the jewel in the crown :)
if its implemented already, I have not understood how to make it work

suggestion:
it would be great to define 2 hotkeys:
- one for translating in the original configuration, like for me: English to Spanish - can be CRTL-SHIFT-Y for example
- and the second one, would translate from Spanish to English: CRTL-SHIFT-X for example
that would be great!!
