### ISSUE TITLE
please support gnome 43 + 44

### ISSUE THREAD

**Issue by skillz-xx** [atareao/translate-assistant#7]
really cannot find anythign better than your tool!
i miss it since upgrading to latest ubuntu

**Comment by atareao** [comment]
Thanks @skillz-xx I will update next week

**Comment by skillz-xx** [comment]
muchissimas gracias!

**Comment by skillz-xx** [comment]
por favoooor

**Comment by skillz-xx** [comment]
I really miss this tool! what does it take to get it compatible again?

**Comment by atareao** [comment]
Updated in last version... waiting for reviewing
