### ISSUE TITLE
Version 8: Sometimes it stops to work, dont know why

### ISSUE THREAD

**Issue by skillz-xx** [atareao/translate-assistant#8]
Hello!

Version 8 works fine, until it doesnt.. at some point it just stops to work, doesnt even translate in the app indicator. something makes it just stop to work.. happened the day before too, then during the day it worked again, until it didnt.. 

Can I somehow access a log file or find out whats going on?

thanks again for your efforts!

**Comment by atareao** [comment]
Please update to version 10 and tell me

**Comment by skillz-xx** [comment]
it works! thank you so much!
